### ISSUE TITLE
Error: Sorry, no video/music uploads, service is not supposed to be used like that

### ISSUE THREAD

**Issue by balibebas** [golotyuk/bashupload#13]
I just made a debugging video and I want to share it with someone on Gitter. Here's what I did:

1. Created a screen recording on macOS
2. Converted to MP4 using `ffmpeg -i some.mov some.mp4`
3. Attempted to upload to bashupload like `curl https://bashupload.com/some.mp4 --data-binary @some.mp4`
5. After some time received the error in title

```
Error: Sorry, no video/music uploads, service is not supposed to be used like that
```

I read the terms and there's nothing in there that says I can't upload videos I create.

**Comment by balibebas** [comment]
One more point I'd like to make. DRM exists and evil companies use it. Attempting to stop people from breaking the law *isn't your job* so **you should allow video uploads** because if someone is concerned enough about their "copywritten" work getting stolen they shouldn't put it on the internet to begin with. So I'm going to upload my video here after I convert it again to a GIF and make it less useful by robbing it of fidelity and robbing me of time:

![out](https://user-images.githubusercontent.com/65664227/92568268-83a54100-f2b1-11ea-8105-35c20eb2b6a5.gif)

**Comment by golotyuk** [comment]
Try now

**Comment by balibebas** [comment]
Thanks for taking a look @golotyuk. I received the same result today, unfortunately:

<img width="830" alt="Screen Shot 2021-01-17 at 7 10 48 PM" src="https://user-images.githubusercontent.com/65664227/104838738-d8a83200-58f7-11eb-94ee-215d27920a21.png">

Perhaps you could reopen this until the issue is resolved somehow? I'm attaching an example mp4 causing the issue.

https://user-images.githubusercontent.com/65664227/104838799-2a50bc80-58f8-11eb-948a-5adf7bc7a2d2.mp4

**Comment by zeroapps** [comment]
Sorry, seems like new updates were not deployed to production. Fixed now.

**Comment by balibebas** [comment]
Works now. Thank you for making this useful service even more useful!

```
=========================

Uploaded 1 file, 5 285 341 bytes

wget https://bashupload.com/4bekH/repro.mp4

=========================
```
