### ISSUE TITLE
file of md5 changed 

### ISSUE THREAD

**Issue by kaizamm** [golotyuk/bashupload#5]
when i upload a file of 20M in mac,and download in linux, i find the md5 changed,and the size of the file changed...

in other words:  the file damaged！

**Comment by golotyuk** [comment]
Can't reproduce that issue (uploading text files from Mac, downloading to Ubuntu). Can you please share the exact command you're using to upload it? And also, if the file is not secret, share the file itself, so we can test everything out. Or maybe just try with other sample file.
Thanks!

**Comment by golotyuk** [comment]
Sorry, no success in reproducing that.
