### ISSUE TITLE
Codeblock shown wrongly on firefox based browsers

### ISSUE THREAD

**Issue by maddovr** [golotyuk/bashupload#7]
![](https://abload.de/image.php?img=screenshot_2019-05-28q1k6d.png)
Firefox 67.0

# Suggestion
Reduce padding in CSS

**Comment by maddovr** [comment]
![](https://abload.de/img/screenshot_2019-05-28q1k6d.png) 
Borked pic link

**Comment by golotyuk** [comment]
Fixed.
